export const INITIAL_FILTERS = [
    "MultipleHitConditionAffected",
    "SplatBloodOnNoDeath",
    "ManuallyRemoveSpentRounds",
    "DisplayName",
    "IsAimedFirearm",
    "SubCategory",
    "Categories",
    "IsAimedHandWeapon",
    "ShareDamage",
    "NPCSoundBoost",
    "haveChamber",
    "DamageCategory",
    "DamageMakeHole",
    "Tags",
    "AttachmentType",
    "DisplayCategory",
    "ConditionLowerChanceOneIn",
    "KnockBackOnNoDeath",
    "RequiresEquippedBothHands",
    "UseEndurance",
    "TwoHandWeapon",
    "EatType",
    "ReplaceOnUse",
    "ReplaceInPrimaryHand",
    "ReplaceInSecondHand",
    "SoundParameter",
    "IconsForTexture",
    "ClothingItem",
    "ClothingItemExtra",
    "ClothingItemExtraOption",

    "EvolvedRecipe" // not implemented
]